---
title: "Webscraping NBA Reference"
output: html_document
---

### Library
First, I am going to load in the `rvest` library.

```{r}
library(rvest)
library(tidyverse)
```

I am feeding my scraper the URL to the list of players.

```{r}
home <- "https://www.basketball-reference.com"
players_url <- paste0(home, "/players")
```

### Finding the A-Z Page Links
I will read this page to find the links to the "per-letter" webpages.

```{r}
webpage <- read_html(players_url)
results_df <- data.frame(
  cbind(
    hover=webpage %>% html_nodes("a") %>% html_text,
    url=webpage %>% html_nodes("a") %>% html_attr("href")
    )
)
head(results_df)
```

I want to narrow down the dataframe to just the pages that are for the starting letter of the players' names.

```{r}
letter_pages <- results_df[which(as.character(results_df[,1]) %in% LETTERS),]
letter_pages[,2] <- paste0(home, letter_pages[,2])
letter_pages
```


### Saving Tables for Each Player
```{r}
# * FUNCTION TO HELP US
get_letter_links <- function(abc_df_row) {
  letter <- tolower(abc_df_row[1])
  url <- abc_df_row[2]
  
  letter_webpage <- read_html(url)
  
  this_letter_df <- data.frame(
  cbind(
    hover=letter_webpage %>% html_nodes("a") %>% html_text,
    url=letter_webpage %>% html_nodes("a") %>% html_attr("href")
  )
)

this_letter_df <- this_letter_df[grepl(paste0("^/players/", letter), this_letter_df[,2]),]
this_letter_df <- this_letter_df[grepl("html", this_letter_df[,2]),]
}

# * MAKE THE DATAFRAMES
all_link_dfs <- apply(letter_pages, 1, get_letter_links)
```

### Consolidation
```{r}
all_players_df <- do.call(rbind, all_link_dfs)
all_players_df <- all_players_df[!duplicated(all_players_df[,2]),]
all_players_df[,2] <- paste0(home, as.character(all_players_df[,2]))
all_players_df[as.integer(runif(10, 0, nrow(all_players_df))),]
```

